package io.shopverify.app;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.extension.*;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.web.server.LocalServerPort;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.*;
import org.openqa.selenium.support.ui.*;
import java.nio.file.*;
import static org.junit.jupiter.api.Assertions.*;
@SpringBootTest(webEnvironment=SpringBootTest.WebEnvironment.RANDOM_PORT,properties={"spring.datasource.url=jdbc:h2:mem:browser;DB_CLOSE_DELAY=-1","spring.jpa.hibernate.ddl-auto=create-drop"})
class LocalShopBrowserTest {
 @LocalServerPort int port; WebDriver d; WebDriverWait wait; String username;
 String url(String path) { return "http://localhost:"+port+path; }
 WebElement element(String id) { return wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector("[data-test='"+id+"']"))); }
 void type(String id,String value) { var e=element(id); e.clear(); e.sendKeys(value); }
 void click(String id) { element(id).click(); }
 void login(String password) { d.get(url("/login")); type("username",username); type("password",password); click("login-button"); }
 void register() { d.get(url("/register")); type("username",username); type("password","TestPass123!"); type("confirmation","TestPass123!"); click("register-button"); wait.until(ExpectedConditions.urlContains("registered")); login("TestPass123!"); wait.until(ExpectedConditions.urlContains("products")); }
 @RegisterExtension final AfterTestExecutionCallback evidence=c->{ if(c.getExecutionException().isPresent() && d!=null) { try { var path=Path.of("target/failure-evidence"); Files.createDirectories(path); Files.write(path.resolve(c.getRequiredTestMethod().getName()+".png"),((TakesScreenshot)d).getScreenshotAs(OutputType.BYTES)); } catch(Exception e) { System.err.println(e.getMessage()); } } };
 @BeforeEach void setup() { username="u"+java.util.UUID.randomUUID().toString().replace("-","").substring(0,20); var options=new ChromeOptions(); if(Boolean.parseBoolean(System.getProperty("headless","true"))) options.addArguments("--headless=new"); options.addArguments("--no-sandbox","--disable-dev-shm-usage","--window-size=1440,1000"); options.setExperimentalOption("prefs",java.util.Map.of("credentials_enable_service",false,"profile.password_manager_enabled",false)); d=new ChromeDriver(options); wait=new WebDriverWait(d,java.time.Duration.ofSeconds(10)); }
 @AfterEach void cleanup() { if(d!=null)d.quit(); }
 @Test void registrationLogoutAndLogin() { register(); assertEquals("Our essentials",element("title").getText()); click("logout"); wait.until(ExpectedConditions.urlContains("logout")); login("TestPass123!"); assertEquals("Our essentials",element("title").getText()); }
 @Test void wrongPassword() { register(); click("logout"); login("WrongPass123!"); assertEquals("Invalid username or password.",element("error").getText()); }
 @Test void duplicateUsername() { register(); click("logout"); d.get(url("/register")); type("username",username); type("password","TestPass123!"); type("confirmation","TestPass123!"); click("register-button"); assertEquals("Username is already taken.",element("error").getText()); }
 @Test void mismatchedConfirmation() { d.get(url("/register")); type("username",username); type("password","TestPass123!"); type("confirmation","OtherPass123!"); click("register-button"); assertEquals("Passwords do not match.",element("error").getText()); }
 @Test void sortingKeepsImageAssociation() { register(); for(String order:java.util.List.of("az","za","lohi","hilo")) { new Select(element("sort")).selectByValue(order); wait.until(ExpectedConditions.urlContains("sort="+order)); var cards=d.findElements(By.cssSelector("[data-test='product']")); var names=cards.stream().map(e->e.findElement(By.cssSelector("[data-test='product-name']")).getText()).toList(); var prices=cards.stream().map(e->new java.math.BigDecimal(e.findElement(By.cssSelector("[data-test='product-price']")).getText().substring(1))).toList(); if(order.equals("az")||order.equals("za")) { var expected=new java.util.ArrayList<>(names); expected.sort(order.equals("az")?java.util.Comparator.naturalOrder():java.util.Comparator.reverseOrder()); assertEquals(expected,names); } else { var expected=new java.util.ArrayList<>(prices); expected.sort(order.equals("lohi")?java.util.Comparator.naturalOrder():java.util.Comparator.reverseOrder()); assertEquals(expected,prices); } for(var card:cards) { var image=card.findElement(By.tagName("img")); String id=card.getDomAttribute("data-id"); String asset=switch(id) { case "1"->"bag"; case "2"->"headphones"; case "3"->"bottle"; case "4"->"notebook"; case "5"->"lamp"; default->"cap"; }; assertTrue(image.getDomAttribute("src").endsWith("/"+asset+".svg")); assertEquals(card.findElement(By.cssSelector("[data-test='product-name']")).getText(),image.getDomAttribute("alt")); assertEquals(Boolean.TRUE,((JavascriptExecutor)d).executeScript("return arguments[0].complete && arguments[0].naturalWidth > 0",image)); } } }
 @Test void quantitiesAndMoney() { register(); d.findElement(By.cssSelector("[data-id='1'] [data-test='add']")).click(); d.get(url("/cart")); type("quantity","2"); click("update"); assertEquals("2",element("cart-count").getText()); assertEquals("$78.00",element("subtotal").getText()); assertEquals("$6.24",element("tax").getText()); assertEquals("$84.24",element("total").getText()); d.navigate().refresh(); assertEquals("2",element("quantity").getDomProperty("value")); click("remove"); assertTrue(element("empty").isDisplayed()); }
 @Test void fullCheckoutAndHistory() { register(); d.findElement(By.cssSelector("[data-id='1'] [data-test='add']")).click(); d.get(url("/cart")); click("checkout"); type("fullName","Demo Shopper"); type("address","123 Test Lane"); click("place-order"); assertEquals("Thank you for your order!",element("confirmation").getText()); assertEquals("0",element("cart-count").getText()); d.get(url("/orders")); assertEquals(1,d.findElements(By.cssSelector(".order")).size()); }
 @Test void cancelCheckout() { register(); d.findElement(By.cssSelector("[data-id='1'] [data-test='add']")).click(); d.get(url("/checkout")); click("cancel"); assertEquals("Your cart",element("title").getText()); assertEquals("1",element("cart-count").getText()); }
 @Test void sessionsAreIsolated() { register(); d.findElement(By.cssSelector("[data-id='1'] [data-test='add']")).click(); click("logout"); String first=username; username="u"+java.util.UUID.randomUUID().toString().replace("-","").substring(0,20); register(); assertEquals("0",element("cart-count").getText()); }
 @Test void detailMatchesCatalog() { register(); var card=d.findElement(By.cssSelector("[data-id='1']")); String name=card.findElement(By.cssSelector("[data-test='product-name']")).getText(); card.findElement(By.tagName("a")).click(); assertEquals(name,element("product-name").getText()); assertEquals("$39.00",element("product-price").getText()); }
}
